### ISSUE TITLE
About FAUST dataset

### ISSUE THREAD

**Issue by qiji77** [riccardomarin/FARM#2]
Hello,
Thank you for your great job, and when I test your method in FAUST dataset, I meet some trobules.
Do these data need to be preprocessed? Or there are some parts in the code that need to be modified? 
I tested on win10 and MATLAB 2017a according to the test steps provided on GitHub.
best,
diaojunqi

**Comment by riccardomarin** [comment]
Hi @qiji77 , sorry for the late reply. 
If I do not forget anything, I think the code should run without errors as it is. What kind of troubles do you meet (e.g., run time error, broken registrations, ...)?

Best,
R

**Comment by qiji77** [comment]
Hello,
Thank you for your reply!
I test 200 scans in the FAUST dataset, and most of the results I got were correct. but some models like test_scan_018.obj and test_scan_036.obj, I got an unsatisfactory result.

![1634025427(1)](https://user-images.githubusercontent.com/30361443/136916421-c716c07c-16c3-479d-86b7-e5e49a6002f1.jpg)
![1634025334(1)](https://user-images.githubusercontent.com/30361443/136916500-135ce1ec-8c7a-424a-8669-bf6fb6855031.jpg)

I followed the instructions on GitHub,
Best 
diaojunqi

**Comment by riccardomarin** [comment]
I see; these results are pretty coherent with some that we obtained during our experiments. Some FAUST examples break left and right labelling and the registration collapse. So I think you are executing the GitHub code in the right way.

But, if I remember correctly, the final correspondence obtained by the registration is further refined with a functional map (i.e., we used the matching given by FARM to initialize another FMAP and then refine it with norm-2,1, the refinement presented in the paper). This is automatic and in such broken cases, the fact that the majority of points are located correctly helps to fix the broken pieces.

**Comment by qiji77** [comment]
Ok, I know that,
and would you like to provide the corresponding calculation script?
It's difficult for me to reproduce it
Anyway, thank you for your help！
diaojunqi

**Comment by riccardomarin** [comment]
I think it will be a bit cumbersome to recover the specific code for that calculation since it has been passed some time: I will investigate if it has been saved by me or some of my co-authors and let you know! (But I would premise I am a bit pessimistic :-\ ).

**Comment by qiji77** [comment]
Ok， Thank you  again.
